version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chatbot
      MYSQL_USER: subyou
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    container_name: flask_app
    command: flask run --host=0.0.0.0
    environment:
      FLASK_ENV: development
      MYSQL_HOST: mysql
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    volumes:
      - .:/app

volumes:
  mysql_data:
