
services:
  web:
    build: .
    container_name: chatbot_flask
    command: flask run --host=0.0.0.0
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
